[2025-10-12T23:55:53.793+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-12T23:55:51.628096+00:00/task_id=bronze_rig_count_pipeline permission to 509
[2025-10-12T23:55:53.793+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-12T23:55:51.628096+00:00/task_id=bronze_rig_count_pipeline permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-12T23:55:51.628096+00:00/task_id=bronze_rig_count_pipeline'
[2025-10-12T23:55:53.835+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-12T23:55:51.628096+00:00/task_id=bronze_rig_count_pipeline permission to 509
[2025-10-12T23:55:53.836+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-12T23:55:51.628096+00:00/task_id=bronze_rig_count_pipeline permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-12T23:55:51.628096+00:00/task_id=bronze_rig_count_pipeline'
[2025-10-12T23:55:53.884+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_pipeline.bronze_rig_count_pipeline manual__2025-10-12T23:55:51.628096+00:00 [queued]>
[2025-10-12T23:55:53.892+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_pipeline.bronze_rig_count_pipeline manual__2025-10-12T23:55:51.628096+00:00 [queued]>
[2025-10-12T23:55:53.892+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2025-10-12T23:55:53.906+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): bronze_rig_count_pipeline> on 2025-10-12 23:55:51.628096+00:00
[2025-10-12T23:55:53.914+0000] {standard_task_runner.py:57} INFO - Started process 12213 to run task
[2025-10-12T23:55:53.917+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_pipeline', 'bronze_rig_count_pipeline', 'manual__2025-10-12T23:55:51.628096+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/ETL_pipeline.py', '--cfg-path', '/tmp/tmplllbyr0j']
[2025-10-12T23:55:53.920+0000] {standard_task_runner.py:85} INFO - Job 33: Subtask bronze_rig_count_pipeline
[2025-10-12T23:55:53.974+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-12T23:55:51.628096+00:00/task_id=bronze_rig_count_pipeline permission to 509
[2025-10-12T23:55:53.975+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-12T23:55:51.628096+00:00/task_id=bronze_rig_count_pipeline permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=ETL_pipeline/run_id=manual__2025-10-12T23:55:51.628096+00:00/task_id=bronze_rig_count_pipeline'
[2025-10-12T23:55:53.976+0000] {task_command.py:415} INFO - Running <TaskInstance: ETL_pipeline.bronze_rig_count_pipeline manual__2025-10-12T23:55:51.628096+00:00 [running]> on host f22a895b55de
[2025-10-12T23:55:54.065+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bech' AIRFLOW_CTX_DAG_ID='ETL_pipeline' AIRFLOW_CTX_TASK_ID='bronze_rig_count_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-10-12T23:55:51.628096+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-12T23:55:51.628096+00:00'
[2025-10-12T23:55:54.068+0000] {bronze_layer.py:275} INFO - Starting bronze layer data ingestion for Baker Hughes Rig Count...
[2025-10-12T23:55:54.068+0000] {bronze_layer.py:52} INFO - Getting rig count data from Baker Hughes...
[2025-10-12T23:55:56.045+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/openpyxl/worksheet/_reader.py:329 UserWarning: Unknown extension is not supported and will be removed
[2025-10-12T23:55:56.053+0000] {bronze_layer.py:79} ERROR - Failed to download rig count data: Number of passed names did not match number of header fields in the file (sheet: NAM Weekly)
[2025-10-12T23:55:56.053+0000] {bronze_layer.py:300} ERROR - ‚ùå Bronze layer ingestion failed: Number of passed names did not match number of header fields in the file (sheet: NAM Weekly)
[2025-10-12T23:55:56.054+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipeline/bronze_layer.py", line 280, in bronze_etl
    rig_count_data = get_rig_count_data(RIG_COUNT_URL)
  File "/opt/airflow/pipeline/bronze_layer.py", line 65, in get_rig_count_data
    df = pd.read_excel(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 486, in read_excel
    data = io.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 1551, in parse
    return self._reader.parse(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 889, in parse
    raise err
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/excel/_base.py", line 851, in parse
    parser = TextParser(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1803, in TextParser
    return TextFileReader(*args, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1679, in _make_engine
    return mapping[engine](f, **self.options)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/python_parser.py", line 124, in __init__
    ) = self._infer_columns()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/python_parser.py", line 515, in _infer_columns
    raise ValueError(
ValueError: Number of passed names did not match number of header fields in the file (sheet: NAM Weekly)
[2025-10-12T23:55:56.074+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_pipeline, task_id=bronze_rig_count_pipeline, execution_date=20251012T235551, start_date=20251012T235553, end_date=20251012T235556
[2025-10-12T23:55:56.087+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 33 for task bronze_rig_count_pipeline (Number of passed names did not match number of header fields in the file (sheet: NAM Weekly); 12213)
[2025-10-12T23:55:56.138+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-10-12T23:55:56.159+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
